version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:3000
    container_name: mre-frontend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      # URL da API Backend rodando no host na porta 3000
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:3000
    restart: unless-stopped

